
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "aie2/add.cc"

extern "C" {

void add_i32_vector(int *A_in, int *B_in, int *C_out) {
  eltwise_vadd<int, int, 16>(A_in, B_in, C_out);
}

} // extern "C"

