
//=============================================================================
// Auto generated by Allo
//=============================================================================
#include <bits/stdc++.h>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <stdfloat>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_kernel.h"
#include "xrt/experimental/xrt_kernel.h" // for xrt::runlist

#include "cxxopts.hpp"
#include "test_utils.h"


int main(int argc, const char *argv[]) {
  // ------------------------------------------------------
  // Parse program arguments
  // ------------------------------------------------------
  cxxopts::Options options("CPP Host Code");
  options.add_options()
    ("xclbin,x", "the input xclbin path", cxxopts::value<std::string>())
    ("instr,i", "path of file containing userspace instructions to be sent to the LX6", cxxopts::value<std::string>())
    ("kernel,k", "the kernel name in the XCLBIN (for instance PP_PRE_FD)", cxxopts::value<std::string>())
    ("verbosity,v", "the verbosity of the output", cxxopts::value<int>()->default_value("0"))
    ("profile,p", "enable profiling", cxxopts::value<bool>()->default_value("false"))
    ("warmup", "number of warmup iterations", cxxopts::value<int>()->default_value("2"))
    ("iters", "number of test iterations", cxxopts::value<int>()->default_value("10"))
    ("trace_sz,t", "trace size", cxxopts::value<int>()->default_value("0"))
    ("trace_file", "where to store trace output", cxxopts::value<std::string>()->default_value("trace.txt"));
  auto vm = options.parse(argc, argv);
  
  int verbosity = vm["verbosity"].as<int>();
  int n_warmup_iterations = vm["warmup"].as<int>();
  int trace_size = vm["trace_sz"].as<int>();
  bool do_profile = vm["profile"].as<bool>();
  int n_test_iterations = vm["iters"].as<int>();

  // Load instruction sequence
  std::vector<uint32_t> instr_v =
      test_utils::load_instr_binary(vm["instr"].as<std::string>());
  if (verbosity >= 1)
    std::cout << "Sequence instr count: " << instr_v.size() << std::endl;

  // ------------------------------------------------------
  // Get device, load the xclbin & kernel and register them
  // ------------------------------------------------------
  unsigned int device_index = 0;
  auto device = xrt::device(device_index);

  // Load the xclbin
  if (verbosity >= 1)
    std::cout << "Loading xclbin: " << vm["xclbin"].as<std::string>() << std::endl;
  auto xclbin = xrt::xclbin(vm["xclbin"].as<std::string>());

  // Load the kernel
  if (verbosity >= 1)
    std::cout << "Kernel opcode: " << vm["kernel"].as<std::string>() << std::endl;
  std::string Node = vm["kernel"].as<std::string>();
  // Get the kernel from the xclbin
  auto xkernels = xclbin.get_kernels();
  auto vaddkernel = *std::find_if(xkernels.begin(), xkernels.end(),
                               [Node, verbosity](xrt::xclbin::kernel &k) {
                                 auto name = k.get_name();
                                 if (verbosity >= 1) {
                                   std::cout << "Name: " << name << std::endl;
                                 }
                                 return name.rfind("VADD", 0) == 0;
                               });
  auto vsubkernel = *std::find_if(xkernels.begin(), xkernels.end(),
                               [Node, verbosity](xrt::xclbin::kernel &k) {
                                 auto name = k.get_name();
                                 if (verbosity >= 1) {
                                   std::cout << "Name: " << name << std::endl;
                                 }
                                 return name.rfind("VSUB", 0) == 0;
                               });

  // Register xclbin
  if (verbosity >= 1)
    std::cout << "Registering xclbin: " << vm["xclbin"].as<std::string>() << std::endl;
  device.register_xclbin(xclbin);

  // Get a hardware context
  xrt::hw_context context(device, xclbin.get_uuid());

  // Get a kernel handle
  auto vaddkernel_ = xrt::kernel(context, vaddkernel.get_name());
  auto vsubkernel_ = xrt::kernel(context, vsubkernel.get_name());

  // instruction
  auto bo_instr0 = xrt::bo(device, instr_v.size() * sizeof(int), XCL_BO_FLAGS_CACHEABLE, vaddkernel_.group_id(1));
  void *bufInstr = bo_instr0.map<void *>();
  memcpy(bufInstr, instr_v.data(), instr_v.size() * sizeof(int));

  auto bo_instr1 = xrt::bo(device, instr_v.size() * sizeof(int), XCL_BO_FLAGS_CACHEABLE, vsubkernel_.group_id(1));
  void *bufInstr1 = bo_instr1.map<void *>();
  memcpy(bufInstr1, instr_v.data(), instr_v.size() * sizeof(int));

  // kernel arguments
  unsigned int opcode = 3;
  auto bo_in0 = xrt::bo(device, 256 * sizeof(int), XRT_BO_FLAGS_HOST_ONLY, vaddkernel_.group_id(3));
  int *bufIn0 = bo_in0.map<int *>();
  std::vector<int> srcVec0;
  std::ifstream ifile0("input0.data");
  if (!ifile0.is_open()) {
    std::cerr << "Error: Could not open input file.\n";
    return 1;
  }
  ifile0.seekg(0, std::ios::end);
  auto ifile0_size = ifile0.tellg();
  ifile0.seekg(0, std::ios::beg);
  if (ifile0_size != 256 * sizeof(int)) {
    std::cerr << "Error: Invalid input file, byte number mismatch.\n";
    return 1;
  }
  std::vector<int> vec0(256);
  ifile0.read(reinterpret_cast<char*>(vec0.data()), 256 * sizeof(int));
  srcVec0.insert(srcVec0.end(), vec0.begin(), vec0.end());
  memcpy(bufIn0, srcVec0.data(), (srcVec0.size() * sizeof(int)));

   auto bo_out0 = xrt::bo(device, 256 * sizeof(int),
                        XRT_BO_FLAGS_HOST_ONLY, vaddkernel_.group_id(4));
  auto bo_out1 = xrt::bo(device, 256 * sizeof(int),
                        XRT_BO_FLAGS_HOST_ONLY, vsubkernel_.group_id(4));
    
  bo_instr0.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  bo_in0.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  auto start = std::chrono::high_resolution_clock::now();
  // gid: (opcode, instr, instr_size, ...)
  auto run0 = vaddkernel_(opcode, bo_instr0, instr_v.size(), bo_in0, bo_out0);
  bo_instr1.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  auto run1 = vsubkernel_(opcode, bo_instr1, instr_v.size(), bo_out0, bo_out1);


  xrt::runlist runlist = xrt::runlist(context);
  runlist.add(run0);
  runlist.add(run1);
  runlist.execute();
  runlist.wait();

  auto end = std::chrono::high_resolution_clock::now();

  float npu_time = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
  std::cout << "NPU execution time: " << npu_time << "us\n";

  ifile0.close();
  bo_out0.sync(XCL_BO_SYNC_BO_FROM_DEVICE);
  bo_out1.sync(XCL_BO_SYNC_BO_FROM_DEVICE);
  int *bufOut1 = bo_out1.map<int *>();
  std::ofstream ofile1("output1.data", std::ios::binary);
  ofile1.write(reinterpret_cast<const char*>(bufOut1 + 0), 256 * sizeof(int));
  ofile1.close();
  
  return 0;
}
