# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: "Self-Hosted CI"

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Init
      run: |
        echo "HOME is $HOME"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Activate conda environment
      shell: bash
      run: |
        source "$HOME/miniconda3/etc/profile.d/conda.sh"
        conda activate allo_ci
        which python3
        python3 --version

    - name: Build project
      shell: bash
      run: |
        echo "Install allo"
        python3 -m pip install -v -e .

    - name: Run unit tests
      shell: bash
      run: |
        echo "🧪 Running tests..."
        python3 -m pytest --ignore=tests/dataflow/aie/gpt2 tests/dataflow/aie -v
