# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: "Self-Hosted CI"

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Init
      run: |
        echo "📁 HOME is $HOME"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Activate conda environment
      shell: bash
      run: |
        source $HOME/.bashrc
        conda activate allo
        which python3
        python3 --version

    - name: Build project
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/allo
        python3 -m pip install -v -e .

    # - name: Run unit tests
    #   shell: bash
    #   run: |
    #     cd $TARGET_DIR/allo/tests/dataflow/aie
    #     echo "🧪 Running tests..."
    #     python3 test_vector.py

